apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: burger-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: burger.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: burger-backend-service
                port:
                  number: 5000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: burger-frontend-service
                port:
                  number: 80
