apiVersion: apps/v1
kind: Deployment
metadata:
  name: burger-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: burger-frontend
  template:
    metadata:
      labels:
        app: burger-frontend
    spec:
      containers:
      - name: burger-frontend
        image: badchan/burger-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: burger-frontend-service
spec:
  type: NodePort            # You can change to LoadBalancer if your k8s supports it
  selector:
    app: burger-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080        # fixed port for access via node IP and this port
