name: CI - Build, Test & SonarQube

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/**'
      - 'k8s/**'

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # required for sonar

      - name: Build frontend Docker image
        run: docker build -t badchan/burger-frontend ./frontend

      - name: Run and test frontend container
        run: |
          docker run -d -p 8080:80 --name test-frontend badchan/burger-frontend
          sleep 5
          curl -f http://localhost:8080
          docker stop test-frontend
          docker rm test-frontend

  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build backend Docker image
        run: docker build -t badchan/burger-backend ./backend

      - name: Run and test backend container
        run: |
          docker run -d -p 5000:5000 --name test-backend badchan/burger-backend
          sleep 5
          curl -f http://localhost:5000/api/burger
          docker stop test-backend
          docker rm test-backend

  sonar-analysis:
    runs-on: ubuntu-latest
    needs: [build-frontend, build-backend]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run SonarQube scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
